version: "3.9"

services:
  api-gateway:
    image: gourav094/vendoriq-api-gateway:latest
    container_name: vendoriq-api-gateway
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
    env_file:
      - ./.env.production
    depends_on:
      - authentication-service
      - email-storage-service
      - ocr-extraction-service
      - chat-service

  authentication-service:
    image: gourav094/vendoriq-auth-service:latest
    container_name: vendoriq-auth-service
    restart: unless-stopped
    ports:
      - "4001:4001"
    environment:
      - NODE_ENV=production
    env_file:
      - ./.env.production

  email-storage-service:
    image: gourav094/vendoriq-email-service:latest
    container_name: vendoriq-email-service
    restart: unless-stopped
    ports:
      - "4002:4002"
    environment:
      - NODE_ENV=production
    env_file:
      - ./.env.production
    depends_on:
      - authentication-service

  ocr-extraction-service:
    image: gourav094/vendoriq-ocr-service:latest
    container_name: vendoriq-ocr-service
    restart: unless-stopped
    ports:
      - "4003:4003"
    environment:
      - NODE_ENV=production
    env_file:
      - ./.env.production

  chat-service:
    image: gourav094/vendoriq-chat-service:latest
    container_name: vendoriq-chat-service
    restart: unless-stopped
    ports:
      - "4005:4005"
    environment:
      - NODE_ENV=production
    env_file:
      - ./.env.production
    volumes:
      - chat_vectordb:/app/data/vectordb
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: "1.0"

  frontend:
    image: gourav094/vendoriq-frontend:latest
    container_name: vendoriq-frontend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - VITE_API_GATEWAY_URL=http://localhost:4000

volumes:
  chat_vectordb:

# docker compose -f docker-compose.prod.yml up -d
